version: "3.7"

services:
  server:
    build:
      context: .
    command: /app/server
    networks:
      - net
  client:
    build:
      context: .
    command: /app/server
    networks:
      - net

networks:
  net: