version: "3.7"

services:
  server:
    image: golang:latest
    command: bash -c "
      go get github.com/andrewdo/go-icmp-data/...
      && cd /go/src/github.com/andrewdo/go-icmp-data && make deps && make
      && mkdir -p /app && mv /go/src/github.com/andrewdo/go-icmp-data/server_out /app/server
      && tail -f /dev/null
      "
    networks:
      - net
  client:
    image: golang:latest
    command: bash -c "
      go get github.com/andrewdo/go-icmp-data/...
      && cd /go/src/github.com/andrewdo/go-icmp-data && make deps && make
      && mkdir -p /app && mv /go/src/github.com/andrewdo/go-icmp-data/shell_out /app/shell
      && tail -f /dev/null
      "
    networks:
      - net
    depends_on:
      - server

networks:
  net: